"""add_severity_recalibration_and_training_flag

Revision ID: aecd859853d9
Revises: 4b3e2274e4f4
Create Date: 2026-06-23 03:28:39.253908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aecd859853d9'
down_revision: Union[str, Sequence[str], None] = '4b3e2274e4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('severity_recalibration_log',
    sa.Column('recal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_cause', sa.String(), nullable=False),
    sa.Column('corridor', sa.String(), nullable=False),
    sa.Column('class_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('n_outcomes_used', sa.Integer(), nullable=False),
    sa.Column('recalibrated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('recal_id')
    )
    op.create_index('idx_sev_recal_cause_corridor', 'severity_recalibration_log', ['event_cause', 'corridor'], unique=False)
    op.add_column('outcomes', sa.Column('processed_for_training', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcomes', 'processed_for_training')
    op.drop_index('idx_sev_recal_cause_corridor', table_name='severity_recalibration_log')
    op.drop_table('severity_recalibration_log')
    # ### end Alembic commands ###
